[phases.setup]
nixPkgs = ["python311", "pip", "sqlite"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[phases.start]
cmd = "gunicorn my_project.wsgi:application --bind 0.0.0.0:$PORT"
